const express = require('express')
const router = express.Router()
const postsController = require('../controllers/posts')
//when request is heard on /feed route, on a path thats in a variable 'postsController' use method 'getFeed' (controllers --> posts.js --> getFeed method)
router.get('/feed', postsController.getFeed)